knpu_oauth2_client:
    clients:
        discord:
            type: discord
            client_id: '%env(DISCORD_CLIENT_ID)%'
            client_secret: '%env(DISCORD_CLIENT_SECRET)%'
            redirect_route: auth_discord_login